java:
  applicationPort: 4550
  image: 'hmctspublic.azurecr.io/hmc/judicial=payment-service:latest'
  ingressHost: hmc-judicial-payment-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: hmc
#  Uncomment once the vault containing the app insights key has been set up
  keyVaults:
    hmc:
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: judicial-payment-service-POSTGRES-USER
          alias: JUDICIAL_PAYMENT_SERVICE_DB_USERNAME
        - name: judicial-payment-service-POSTGRES-PASS
          alias: JUDICIAL_PAYMENT_SERVICE_DB_PASSWORD
        - name: judicial-payment-service-POSTGRES-HOST
          alias: JUDICIAL_PAYMENT_SERVICE_DB_HOST
        - name: judicial-payment-service-POSTGRES-PORT
          alias: JUDICIAL_PAYMENT_SERVICE_DB_PORT
        - name: judicial-payment-service-POSTGRES-DATABASE
          alias: JUDICIAL_PAYMENT_SERVICE_DB_NAME
          environment:
            CFT_HEARING_SERVICE_DB_OPTIONS: "?stringtype=unspecified&gssEncMode=disable"
  environment:
